name: Generate a build and push to another branch

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push
    
    strategy:
      matrix:
        node-version: [14.x]
      
    steps:
      - name: git-checkout
        uses: actions/checkout@v2
        with:
          node-version: 14

      - name: Install all dependencies
        run: npm install

      - name: Build
        run: npm run build # The build command of your project

      - name: Push
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: main
          FOLDER: main
          MESSAGE: "Build: " # The commit message
